import type { Metadata } from "next";
import { Geist, Geist_Mono , Averia_Serif_Libre, Inter, Newsreader } from "next/font/google";
import "./globals.css";

//footer and navbar import
import Navbar from "../components/navbar";
import Footer from "../components/footer"; // Make sure to import your Footer component

// Fonts
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });
const averiaSerif = Averia_Serif_Libre({
    variable: "--font-averia",
    subsets: ["latin"],
    weight: ["300", "400", "700"],
});
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const newsreader = Newsreader({
    variable: "--font-newsreader",
    subsets: ["latin"],
    weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Yíká Inc",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${averiaSerif.variable} ${inter.variable} ${newsreader.variable}`}>
        <head>
            <link
                href="https://api.fontshare.com/v2/css?f[]=satoshi@300,400,500,700&display=swap"
                rel="stylesheet"
            />
        </head>
        <body className="font-satoshi antialiased flex flex-col min-h-screen">
        <Navbar />
        <div className="flex-1 pt-[76.87px]"> {/* flex-1 makes this expand */}
            <div className="max-w-full mx-auto w-full">{children}</div>
        </div>
        <Footer />
        </body>
        </html>
    );
}